---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.general
    - hpe.ilo
#  pre_tasks:
#      - include_vars: /root/template/HPE/vars/vars.yaml    
#  vars_files:
#    - vars.yaml
  tasks:
  - name: Get logical drives details
    get_logical_drives_details:
      baseuri: "10.1.17.3" #"{{ baseuri }}"
      username: "admin" #"{{ username }}"
      password: "admin123" #"{{ password }}"
    register: logical_drives_data

  - name: Check if logical drives exists in the server
    debug:
      msg: "No logical drives present in the server"
    when: logical_drives_data['logical_drives_details'] | length | int == 0

  - name: Delete all logical drives
    delete_all_logical_drives:
      baseuri: "10.1.17.3" #"{{ baseuri }}"
      username: "admin" #"{{ username }}"
      password: "admin123" #"{{ password }}"
    register: result
    when: logical_drives_data['logical_drives_details'] | length | int > 0

  - name: Status
    debug:
      msg: "{{ result }}"
    when: logical_drives_data['logical_drives_details'] | length | int > 0
