---
# - name: JsonQuery Playbook
#   hosts: localhost
#   tasks:
#     - name: Download JSON content play
#       uri:
#         url: https://jsonplaceholder.typicode.com/users
#         url: http://10.1.14.11/ks/test
#         method: GET
#         return_content: yes
#       register: test

#     - name: Cat file
#       ansible.builtin.command: cat /root/template/HPE/users
#       register: jsoncontent

#     - name: Business Card
#       debug: msg="{{ test.json | json_query(jmesquery) }}"
#       vars:
#         jmesquery: "[*].{Name: name, Email: email, Phone: phone, CompanyName: company.name, WebSite: website, City: address.city}"
#         jmesquery: "[*].MACAddress"

- hosts: localhost
  tags: s21
  gather_facts: no
  vars:
    images:
      - foo
      - bar
  tasks:
    - shell: "echo result-{{item}}"
      register: "r"
      with_items: "{{images}}"

    - debug: var=r

    - debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
      with_items: "{{r.results}}"

    - debug: msg="Gets printed only if this item changed - {{item}}"
      when: "{{item.changed == true}}"
      with_items: "{{r.results}}"
