---
# tasks file for get_network_protocols
- name: Get Network Protocols
  collections:
    - community.general
    - hpe.ilo
  community.general.redfish_info:
    category: Manager
    command: GetNetworkProtocols
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    # auth_token: "{{ result.session.token }}"
  register: result_attr
